#autogenerated by sqlautocode

from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relation

engine = create_engine('mysql+pymysql://root:123456@localhost:3306/pythontest')
DeclarativeBase = declarative_base()
metadata = DeclarativeBase.metadata
metadata.bind = engine

class Role(DeclarativeBase):
    __tablename__ = 'roles'

    __table_args__ = {}

    #column definitions
    id = Column('id', INTEGER(display_width=11), primary_key=True, nullable=False)
    name = Column('name', VARCHAR(length=64))

    #relation definitions


class Test(DeclarativeBase):
    __tablename__ = 'test'

    __table_args__ = {}

    #column definitions
    id = Column('id', INTEGER(display_width=10), primary_key=True, nullable=False)
    name = Column('name', VARCHAR(length=64))

    #relation definitions


class User(DeclarativeBase):
    __tablename__ = 'users'

    __table_args__ = {}

    #column definitions
    id = Column('id', INTEGER(display_width=11), primary_key=True, nullable=False)
    role_id = Column('role_id', INTEGER(display_width=11), ForeignKey('roles.id'))
    username = Column('username', VARCHAR(length=64))

    #relation definitions


